[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"

[invariant]
runs = 128 #运行次数
depth =  128 #单次运行中的函数调用次数
fail_on_revert = false

#fail_on_ervert = false决定了当模糊测试器（fuzzer）在执行随机交易序列时，遇到任何一笔交易回退（revert）时，是否立即将该次运行标记为“失败”

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
